### ISSUE TITLE
Web button

### ISSUE THREAD

**Issue by marll** [satispay/online-api-php-sdk#10]
Salve,
per eseguire il pagamento non vorrei utilizzare lo script web button ma php. Potreste fornirmi qualche esempio?
Grazie

**Comment by adnsio** [comment]
Ciao,

lo script web-button è un applicazione client-side, puoi utilizzarlo su qualsiasi tecnologia.

La parte server-side è solamente la user-callback, devi effettuare un "create charge" con lo user id che ti viene passato via POST. Trovi più dettagli nella documentazione: https://s3-eu-west-1.amazonaws.com/docs.online.satispay.com/index.html#section/Web-Button/User-callback

**Comment by marll** [comment]
Ciao,
piu' che altro volevo sapere se potevo evitare l'utilizzo dello script ed eseguire una post ad una mia classe php che poi, utilizzando la libreria, avviasse il pagamento.
Avrei altri dubbi:
-il data-key dovrebbe essere legato al sito di ecommerce invece sembra sia legato al mio numero di telefono. Durante i test mi aspetto di poter acquistare (utilizzando lo stesso data-key) inserendo anche un numero diverso dal mio (simulando così l'utente finale). Dai test fatti non sembra possibile
-La post create charge deve essere inviata subito la ricezione dell'uuid o dopo la conferma dell'utente (attraverso la visualizzazione di una pagina sul sito)?Se no in quale fase avviene l'approvazione?
-Quando eseguo le  Get Charge con il valore che mi viene ritornato in {uuid} lo status finale è sempre FAILURE. Come faccio a capire qual'è il problema?
-Utilizzando lo script https://staging.online.satispay.com/button.min.js alla fine del pagamento mi viene ritornato il messaggio:
      **Per concludere il pagamento apri l'app e accetta la richiesta entro 3 ore**
In questo caso il sito di ecommerce come fa a sapere se l'utente confermerà il pagamento?
Inoltre questo messaggio mi viene ritornato anche quando lo status della Get change è FAILURE
-Utilizzando lo script https://staging.online.satispay.com/button.min.js c'è un modo per fare ritornare l'esito dell'operazione alla pagina che lo ha avviato?

Grazie
