### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by bessone** [satispay/online-api-php-sdk#4]
Ciao,

API documentation says about Italian and English messages, there is a parameter to indicate in which language will the Satispay form be shown?

Grazie

**Comment by alessiodionisi** [comment]
Ciao,
cosa intendi per messaggi e form? Il web button?

**Comment by bessone** [comment]
Ciao, intendo il form in cui si inserisce il numero di telefono, quando viene effettuato il redirect dal sito ai server satispay, l'interfaccia è sempre in italiano, dalla documentazione (http://bit.ly/API-online-integration) parla di interfaccia in italiano o inglese, ma dalla documentazione REST (https://s3-eu-west-1.amazonaws.com/docs.online.satispay.com/index.html) non c'è un parametro per indicare la lingua da usare nel form satispay dopo la redirezione dal sito originale.

**Comment by alessiodionisi** [comment]
Ciao quel documento spiega come fare un integrazione custom e da delle linee guida.
Per ora non c'è nessun sistema che reindirizza su un nostro server per pagare, l'unico disponibile già pronto è il web button.

Ti anticipo però che `Checkout.php` serve ad utilizzare una nuova API che implementa questo flow di pagamento, ma ancora non è stato documentato.

**Comment by bessone** [comment]
Forse mi sono spiegato male, io sto proprio usando l'endpoint di checkout (attraverso la tua PHP SDK) perchè ho trovato la stessa identica integrazione nei moduli per Prestashop e per Magento che sto utilizzando su alcuni progetti.
Da qui per fare il modulo per Drupal Commerce o seguito la stessa linea, traducendo solo il codice.

Per l'appunto dove aver fatto il checkout eseguo la redirezione verso i vostri server, ma non c'è modo per indicare in che lingua vedere l'interfaccia? Non è una cosa bloccante, ma era giusto per capire di fare tutto nel modo più corretto possibile.

**Comment by alessiodionisi** [comment]
Perfetto ora è chiaro, di default nella nuova versione di web button e checkout prenderà la lingua del browser (puoi testarla in staging). Si potrà impostare una lingua "forzata" con `data-locale` nel web button.

**Comment by bessone** [comment]
Grazie per il chiarimento, quindi in fase di checkout con le API (non usando il web button js) non c'è modo di forzarla? 
Il mio caso ad esempio è che ho OS e Browser in inglese, ma navigo un sito in italiano, l'interfaccia di satispay la vedrei in inglese, è corretto?

**Comment by alessiodionisi** [comment]
Si
