### ISSUE TITLE
Checkout Id

### ISSUE THREAD

**Issue by bessone** [satispay/online-api-php-sdk#7]
Ciao Alessio,

sto scrivendo una nuova integrazione per Drupal 8, un po' più robusta e complessa di quella per Drupal 7 tenendo traccia anche delle transazioni.

Sto usando il metodo checkout delle API, quello non documentato ma che ho visto utilizzano tutti i moduli per i vari ecommerce.
Ho notato che nelle varie integrazioni per identificare l'ordine durante il callback viene utilizzato il numero d'ordine inserito in fase di checkout nel campo metadata, mi chiedevo se fosse possibile usare direttamente gli uuid di satispay, per avere maggiore robustezza del tutto.

Quando si usa il metodo di checkout viene restituito un checkout id, ma quando viene chiamato il callback ho solo il charge id, in questo modo non posso collegarli tra loro.
Ho visto che nel return url vengono passati entrambi gli id in get, non è possibile farlo anche per il callback? O ancora meglio passare il checkout id via json quando si fa il get charge?

Spero di essermi spiegato ;)

Grazie!

**Comment by bessone** [comment]
E' possibile avere qualche notizia a riguardo? Se c'è bisogno di maggiori dettagli sono a disposizione.
Grazie

**Comment by alessiodionisi** [comment]
Ciao,

devi utilizzare le api in modo standard, passa il tuo orderid nel checkout e lo riceverai poi nel webhook

**Comment by alessiodionisi** [comment]
Ciao,

con il checkout ci occupiamo noi del webhook quindi se ci passi l'orderid nei metadata lo aggiungiamo nei metadata finali della charge.

Nel callback leggi la charge con le api e così puoi riprendere l'orderid dai metadata.

**Comment by bessone** [comment]
Ciao Alessio,

è quello che sto già facendo con l'integrazione con Drupal 7, dove nel database è prevista una sola transazione per ordine (non sono gestiti nativamente refund e simili).

Viceversa nel nuovo sistema possono esserci più transazioni per ogni singolo ordine, quindi usare l'orderid nel callback diventerebbe non così robusto.

La cosa che ho notato è che quando l'utente viene reindirizzato al sito in querystring ci sono chargeid e checkoutid, non potrebbe esserci la stessa cosa anche nel callback?

La domanda che mi sono fatto è questa: al momento della creazione di un checkout è anche generata la charge o questa viene effettivamente creata solo quando l'utente dal vostro portale inserisce il proprio numero di telefono? Non essendo documentato il checkout sono andato un po' a tentativi.

**Comment by alessiodionisi** [comment]
Viene generata dopo, non conosco drupal ma prova a passarti l'id della transazione e non dell'ordine.

**Comment by bessone** [comment]
Ciao Alessio,

non è tanto la questione Drupal, ma una questione logica nel trattare più transazioni. Provo a spiegarti le mie due situazioni tipo:

**Singola transazione nel db**
1. Il cliente completa il checkout sul sito, chiamo il metodo create della classe Checkout delle API, passandogli in metadata il mio orderId. Salvo il messaggio di risposta nel mio database, usando come remoteId il checkoutId che mi viene restituito.
2. L'utente va sul sito di Satispay e fa il pagamento.
3. Nella pagina di callback uso il metodo get delle classe Callback, identifico la transazione dal orderId nel campo metadata, così aggiorno lo stato della mia transazione nel database.

Qui va tutto bene, perchè nel database le relazione ordine-transazione è uno a uno.

**Multiple transazioni nel db**
1. Il cliente completa il checkout sul sito, chiamo il metodo create della classe Checkout delle API, passandogli in metadata il mio orderid. Salvo il messaggio di risposta nel mio database, usando come remoteId il checkoutId che mi viene restituito.
2. L'utente va sul sito di Satispay e fa il pagamento.
3. Nella pagina di callback uso il metodo get delle classe Callback, avendo la possibilità di avere più transazioni per un ordine (in caso di pagamenti splittati, refund, ecc...) non posso usare l'orderId come identificativo della transazione. 
Come identificativo della transazione nel mio database ho il checkoutId, ma in GET mi viene passato solo il chargeId, così non ho modo di fare un match.

Al contrario nel returnUrl in GET mi viene passato sia il chargeId che il checkoutId, come puoi vedere dai log: 
```
54.171.124.200 - - [18/Oct/2017:18:02:41 +0200] "GET /en/payment/notify/satispay?uuid=7c96c4c3-5428-4313-b3f6-681f29d87953&status=SUCCESS HTTP/1.1" 200 5
0.0.0.0 - - [18/Oct/2017:18:02:41 +0200] "GET /en/checkout/11/payment/return?charge_id=7c96c4c3-5428-4313-b3f6-681f29d87953&checkout_id=0bc3df54-2511-4b78-b17a-6eb26dd1401c&ok=true&error_code=&message= HTTP/1.1" 302 340
```
Come sai non posso basarmi sull'aggiornamento della transazione sul return, l'utente potrebbe chiudere la finestra del browser, avere problemi di sorta.

Se il metodo create del Checkout non può restituire il chargeId perchè non è ancora stato creato sul vostro sistema, non è possibile almeno far si che il callback mi restituisca anche il riferimento al checkout con il checkoutId nella GET o nella risposta json?

**Comment by adnsio** [comment]
Ciao,
volevo informarti che ora puoi trovare il checkout id nei metadata della charge che viene creata.
